apiVersion: v1
kind: Service
metadata:
  name: daca-service
spec:
  type: NodePort
  ports:
  - port: 4000
  selector:
    run: daca-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daca-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: daca-deployment
  template:
    metadata:
      labels:
        run: daca-deployment
    spec:
      containers:
      - name: daca-v1
        image: daca:v1
  